### PR TITLE
General refactoring

### PR DESCRIPTION
**Pull request by drusepth**
I've been staring at this code long enough, it's time to hit it with a hard hit of metaprogramming so it's not so bad.

### CODE REVIEW

**Comment by drusepth** [comment]
@Cantido All the tests you wrote make this so awesome to do. Thanks!

**Comment by Cantido** [comment]
I'm happy that they are paying off! That's what I wrote them for :smile_cat:

**Comment by drusepth** [comment]
Watching https://codeclimate.com/github/indentlabs/Indent/compare/rapid-refactor is mighty fun :)

**Comment by Cantido** [comment]
Doesn't refactoring code just feel great?

**Comment by drusepth** [comment]
It does! :)

**Pull request merged**
